### PR TITLE
Block Editor Tools: `useInnerBlocks` return child blocks instead of the parent block

### PR DESCRIPTION
**Pull request by renatonascalves**
Based on its name and description, `useInnerBlocks` should be returning the array of inner blocks but it currently returns the parent block IF the block has inner blocks or an empty `array` if the block does not have inner blocks.

Screenshot 2023-08-14 at 00 51 56

So it works sort of a line a `useHasInnerBlocks`. This hook is used in other hooks internally, in the `useInnerBlockIndex`, etc. 

I assume this worked before correctly or people assumed it worked before since it returned the parent block inside an `array`, instead of the child/inner blocks. But the current behavior is not accurate, IMO.

For Alley devs: we have [many instances](https://l.alley.dev/e0a4d4953c), or copies, of this block we might need to update or confirm if they are behaving properly.

### CODE REVIEW

**Comment by mogmarsh** [comment]
I left comments in Slack, but I think it is working as expected currently. I ran the same test in my browser and got back the expected result. Perhaps the first step should be to write some Jest tests for this and other hooks and then go from there if any of the tests don't pass.

**Review by kevinfodness — APPROVED** [review]
🍣

**Comment by renatonascalves** [comment]
Actually, this needs a bit more investigation. I need to confirm why this is not working correctly on my WordPress 6.3 instance on my machine but it is returning properly in others. So my fix here would actually be a regression.

I'll add tests as well before moving on with it.

**Comment by renatonascalves** [comment]
This turned out to be invalid. I'm not sure what happened before. My guess is that browser played a part into the problem since that's the only thing I did to change the results, clear the browser cache.

**Pull request closed without merging**
